module.exports = {
    User: require('./User'),
    Patient: require('./Patient'),
    Doctor: require('./Doctor'),
    Admin: require('./Admin'),
    Appointment: require('./Appointment'),
    Payment: require('./Payment'),
    Specialty: require('./Specialty'),
    City: require('./City'),
    Announcement: require('./Announcement'),
    SystemSetting: require('./SystemSetting'),
    SitePage: require('./SitePage'),
    ServiceItem: require('./ServiceItem'),
    BlogPost: require('./BlogPost'),
    VisitNote: require('./VisitNote'),
    FamilyMember: require('./FamilyMember'),
    MedicalHistoryEntry: require('./MedicalHistoryEntry'),
    Testimonial: require('./Testimonial'),
    ContactMessage: require('./ContactMessage'),
};
